### ISSUE TITLE
Cannot update endVal and options simultanously

### ISSUE THREAD

**Issue by wecraw** [inorganik/ngx-countUp#100]
```
[ X ] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 

```
Angular: 13.3.11
Angular CLI: 13.3.11
ngx-countup: 13.1.0
```

#### Description

`endVal` and `options` cannot be simultaneously. 

#### Repro steps

1. Update `useOptions()` function to include an update to `endVal`.
2. Click "Test options change", observe that the endVal is updated and reanimated, but the new options are not reflected until subsequent calls of the `useOptions()`.

#### Notes

Detailed discussions [here](https://github.com/inorganik/ngx-countUp/pull/99).

> The reason is because in the directive, there's an if/else statement in ngOnChanges, making it so it's an either/or situation.

**Comment by inorganik** [comment]
Resolved with #101 , released in 13.2.0
