### ISSUE TITLE
angular 9

### ISSUE THREAD

**Issue by stewwan** [inorganik/ngx-countUp#40]
```
[ ] Bug
[x] Build issue
[ ] Feature request
```

hello there! can you update deps to angular 9?

**Comment by inorganik** [comment]
PRs welcome! Don't know how soon I'll get around to it...

**Comment by inorganik** [comment]
I just published 7.3.1 of `ngx-countup` which supports Angular versions 7-10 (tested in all versions), so this issue is resolved.
