### ISSUE TITLE
Can't bind to 'endVal'

### ISSUE THREAD

**Issue by hawrancz99** [inorganik/ngx-countUp#43]
```
[ x ] Bug
[ ] Build issue
[ ] Feature request
```

#### Version info 
"@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "countup.js-angular2": "^7.3.0",
    "ngx-countup": "^7.3.0",
    "ngx-scrollspy": "^1.2.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"

```
Angular: "@angular-devkit/build-angular": "~0.900.7",
Angular CLI: "~9.0.3",
"ngx-countup": "^7.3.0",
```

#### Description

Hi, i am trying to bind to endVal but for some reason it throws this error : _Can't bind to 'endVal' since it isn't a known property of 'div'.ng_
` <div class="value" [countUp]="options" [endVal]="d.displayValue"></div>`
Thanks!

**Comment by inorganik** [comment]
Looks like you have the old package and the new one installed - remove the old one and it should solve your issue. (countup.js-angular2 was renamed to ngx-countup).

```
npm uninstall countup.js-angular2
```

**Comment by hawrancz99** [comment]
It didn't work neither with ngx-countup or countup.js-angular2. It started working specificaly only with countup.js-angular2@6.0.2. Anyway, thanks a lot, it's working now.

**Comment by IgorKurkov** [comment]
Unfortunately not work with the new version `ngx-countup@7.3.3` 
`Can't bind to 'endVal'` error still appear...

**Comment by inorganik** [comment]
Sorry I just took a closer look. The input changed from `[endVal]` to `[countUp]` at version 2.0. There's an example in [the README](https://github.com/inorganik/ngx-countUp#usage)

**Comment by IgorKurkov** [comment]
Ok! Sorry that disturb you! Just notice a bug, and it is not a bug :)
