### ISSUE TITLE
Make the animate function public

### ISSUE THREAD

**Issue by obumnwabude** [inorganik/ngx-countUp#72]
```
[ ] Bug
[ ] Build issue
[*] Feature request
```

#### Version info 

```
Angular: 13
Angular CLI: 13
ngx-countup: 13
```

#### Description

This is a cool library. Thanks for building it. I've used it in multiple projects.

Currently, there is no way to reanimate the count up when the developer wants to do so. For example, the developer may want to be reanimating after every interval of some seconds. Or the developer may want to reanimate the countUp whenever the countUp is scrolled into view (especially when it is not among the first things the user sees on the page). 

Making the [`private animate()`](https://github.com/inorganik/ngx-countUp/blob/9472c6302aa005382008477609558f17a54c1cfc/projects/count-up/src/lib/count-up.directive.ts#L64) method on the `CountUpDirective` public should solve this problem. This way the developer can use `@ViewChild` to select the directive and call animate when they want to. 

I was surprised that the method in question was private. Didn't know what motivated making it private in the first place so that's why I opened this issue first, rather than sending a pull request with the change directly.

**Comment by inorganik** [comment]
the countUp instance itself is public, but calling start() on that will trigger a lot of change detection. I think your solution is better, make animate public. I don't know if there was ever a reason for making it private. Would you like to make a PR please?
