### ISSUE TITLE
Angular 15 compability

### ISSUE THREAD

**Issue by Ilkhom-S** [inorganik/ngx-countUp#79]
[Feature request]
```
[ ] Bug
[ ] Build issue
[ ] Feature request
```

Angular 15

```
Angular:
Angular CLI:
ngx-countup: 
```

#### Description

Can you build angular 15 compability version.

**Comment by inorganik** [comment]
How is the current version not compatible?

**Comment by Ilkhom-S** [comment]
No compatible,  just warning

**Comment by inorganik** [comment]
I can't reproduce. I new'd up an angular 15 project, installed ngx-countup, imported the module and added the directive to an element with a number value. It did a prod build  without any warnings or errors. With ng serve, it animated as expected.

Unless you can provide me with repro steps and what error you are getting, going to close.

**Comment by Ilkhom-S** [comment]
Hello, 

You can close. Sorry. It was from another package. I confirm that package working as expected in angular 15
